apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
metadata:
  name: ubuntu-bionic
spec:
  domain:
    devices:
      disks:
        - name: containerdisk
          volumeName: containervolume
          disk:
            bus: virtio
        - name: cloudinitdisk
          volumeName: cloudinitvolume
          disk:
            bus: virtio
      interfaces:
      - name: default
        bridge: {}
    resources:
      requests:
        memory: 256M
  networks:
  - name: default
    pod: {}
  volumes:
    - name: containervolume
      containerDisk:
        image: quay.io/quamotion/ubuntu-container-disk:18.04
    - name: cloudinitvolume
      cloudInitNoCloud:
        userData: |-
          #cloud-config
          users:
            - name: kubevirt
              lock-passwd: false
              passwd: $1$SaltSalt$31kYxns5FwSKLI1ASNtey1
